version: '3'

services:

  release-manager-db:
    image: mariadb/server:10.3.13
    container_name: release-manager-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: services-db
      MYSQL_ROOT_PASSWORD: here-we-do-not-need-secure-password
